include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    unawaited_futures: true

formatter:
  page_width: 120
  trailing_commas: preserve
