name: my_life
publish_to: none

version: 0.1.0+1

environment:
  sdk: ^3.13.0

workspace:
  - packages/*

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  phosphor_icons: ^3.0.1
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_svg: ^2.2.2
  lottie: ^3.3.2
  talker_flutter: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  theme_tailor_annotation: ^3.1.1
  slang: ^4.19.0
  slang_flutter: ^4.19.0
  get_it: ^9.3.0
  injectable: ^3.0.0
  my_life_debug: any
  my_life_core: any
  my_life_ui_kit: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  flutter_gen_runner: ^5.12.0
  theme_tailor: ^3.1.1
  injectable_generator: ^3.0.2
  melos: ^8.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

melos:
  useRootAsPackage: true
  scripts:
    build:
      description: Generate code, format and analyze every workspace package.
      steps:
        - dart run slang
        - melos exec --depends-on=build_runner --order-dependents -c 1 -- dart run build_runner build
        - melos exec -- dart format lib
        - melos exec -- dart analyze
